# Generated by Django 6.0.2 on 2026-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_spending',
            field=models.BooleanField(default=False),
        ),
    ]
