# Generated by Django 6.0.2 on 2026-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_show_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text="User's preferred language for AI responses and interface.", max_length=5),
        ),
    ]
