from django.db import models

from vehicles.models import Vehicle


class TaskCatalog(models.Model):
    """Catalog of maintenance tasks per vehicle, generated by AI."""

    class Source(models.TextChoices):
        AI_GENERATED = 'ai_generated', 'IA'
        USER_CREATED = 'user_created', 'Usuario'

    vehicle = models.ForeignKey(
        Vehicle,
        on_delete=models.CASCADE,
        related_name='task_catalog',
    )
    task_code = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    interval_km = models.PositiveIntegerField(null=True, blank=True)
    interval_months = models.PositiveIntegerField(null=True, blank=True)
    is_safety_critical = models.BooleanField(default=False)
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.AI_GENERATED,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'task_catalog'
        unique_together = [('vehicle', 'task_code')]
        verbose_name = 'Tarea de catálogo'
        verbose_name_plural = 'Catálogo de tareas'

    def __str__(self):
        return f"{self.name} ({self.vehicle})"


class MaintenanceEvent(models.Model):
    """Records of completed maintenance - what the user registers."""

    vehicle = models.ForeignKey(
        Vehicle,
        on_delete=models.CASCADE,
        related_name='maintenance_events'
    )
    task_code = models.CharField(max_length=50)
    date = models.DateField()
    km_at_service = models.PositiveIntegerField()
    notes = models.TextField(blank=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'maintenance_events'
        verbose_name = 'Evento de mantenimiento'
        verbose_name_plural = 'Eventos de mantenimiento'
        ordering = ['-date', '-created_at']

    def __str__(self):
        return f"{self.task_code} - {self.vehicle} ({self.date})"


class Accessory(models.Model):
    """Accessories and modifications installed on a vehicle."""

    vehicle = models.ForeignKey(
        Vehicle,
        on_delete=models.CASCADE,
        related_name='accessories',
    )
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'accessories'
        verbose_name = 'Accesorio'
        verbose_name_plural = 'Accesorios'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.vehicle})"


def event_attachment_path(instance, filename):
    """Generate upload path: attachments/user_<id>/event_<id>/<filename>"""
    user_id = instance.event.vehicle.user_id
    return f'attachments/user_{user_id}/event_{instance.event_id}/{filename}'


class EventAttachment(models.Model):
    """Attachments (invoices, photos) linked to a MaintenanceEvent."""

    class FileType(models.TextChoices):
        PDF = 'pdf', 'PDF'
        IMAGE = 'image', 'Imagen'

    class AnalysisStatus(models.TextChoices):
        PENDING = 'pending', 'Pendiente'
        PROCESSING = 'processing', 'Procesando'
        COMPLETED = 'completed', 'Completado'
        FAILED = 'failed', 'Fallido'

    event = models.ForeignKey(
        MaintenanceEvent,
        on_delete=models.CASCADE,
        related_name='attachments'
    )
    file = models.FileField(upload_to=event_attachment_path)
    file_type = models.CharField(max_length=10, choices=FileType.choices)
    original_filename = models.CharField(max_length=255)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    analysis_status = models.CharField(
        max_length=20,
        choices=AnalysisStatus.choices,
        default=AnalysisStatus.PENDING,
    )
    analysis_result = models.TextField(blank=True, null=True)
    analysis_error = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'event_attachments'
        verbose_name = 'Adjunto de evento'
        verbose_name_plural = 'Adjuntos de eventos'
        ordering = ['-uploaded_at']

    def __str__(self):
        return f"{self.original_filename} ({self.event})"
