# Generated by Django 6.0.2 on 2026-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('km_at_service', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de mantenimiento',
                'verbose_name_plural': 'Eventos de mantenimiento',
                'db_table': 'maintenance_events',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('dismissed', 'Descartada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea de mantenimiento',
                'verbose_name_plural': 'Tareas de mantenimiento',
                'db_table': 'maintenance_tasks',
                'ordering': ['priority', 'due_date', 'due_km'],
            },
        ),
        migrations.CreateModel(
            name='TaskCatalog',
            fields=[
                ('task_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motocicleta'), ('car', 'Coche')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('default_interval_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_safety_critical', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tarea de catálogo',
                'verbose_name_plural': 'Catálogo de tareas',
                'db_table': 'task_catalog',
            },
        ),
    ]
