# Generated by Django 6.0.2 on 2026-02-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceevent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='completed_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_task', to='maintenance.maintenanceevent'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='created_from_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_events', to='maintenance.maintenancetask'),
        ),
    ]
