# Generated by Django 6.0.2 on 2026-02-14 16:36

import django.db.models.deletion
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=maintenance.models.event_attachment_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Imagen')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.maintenanceevent')),
            ],
            options={
                'verbose_name': 'Adjunto de evento',
                'verbose_name_plural': 'Adjuntos de eventos',
                'db_table': 'event_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
