# Generated by Django 6.0.2 on 2026-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceevent',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
