# Generated by Django 6.0.2 on 2026-02-13 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motocicleta'), ('car', 'Coche')], default='motorcycle', max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('current_km', models.PositiveIntegerField()),
                ('displacement', models.PositiveIntegerField(blank=True, help_text='Cilindrada en cc', null=True)),
                ('usage_type', models.CharField(choices=[('city', 'Ciudad'), ('mixed', 'Mixto'), ('highway', 'Carretera')], default='mixed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
