# Generated by Django 6.0.2 on 2026-02-22 22:24

import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=vehicles.models.vehicle_document_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Imagen')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, help_text='Ej: Manual de usuario, Ficha técnica', max_length=200)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Documento del vehículo',
                'verbose_name_plural': 'Documentos del vehículo',
                'db_table': 'vehicle_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
