# Generated by Django 6.0.2 on 2026-04-18 15:06

import django.db.models.deletion
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaragePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=social.models.garage_photo_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_photos', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'garage_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
