# Generated by Django 6.0.2 on 2026-06-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_garagephoto_is_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garagephoto',
            options={'ordering': ['-is_cover', '-uploaded_at']},
        ),
    ]
